
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kubemrdtjwlrpkbnrzrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1YmVtcmR0andscnBrYm5yenJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTczODgsImV4cCI6MjA2Mjg5MzM4OH0.7laAzfH7f5x0vtko8kQTW7f8XgSzSzxRsG7N3Cm7EKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
